"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Tab = "Menu" | "Reservations" | "Orders" | "Testimonials" | "Gallery";
const tabs: Tab[] = ["Menu", "Reservations", "Orders", "Testimonials", "Gallery"];
const input = "border-[3px] border-[var(--ink)] bg-[var(--paper)] p-2 text-xs min-w-0";

export default function AdminDashboard() {
  const router = useRouter(); const [tab, setTab] = useState<Tab>("Menu"); const [rows, setRows] = useState<any[]>([]); const [form, setForm] = useState<Record<string, string>>({}); const token = typeof window === "undefined" ? "" : localStorage.getItem("gt-admin-token") || "";
  const endpoint = `/api/admin/${tab.toLowerCase()}`;
  const load = async () => { const response = await fetch(endpoint, { headers: { Authorization: `Bearer ${token}` } }); if (response.status === 401) return router.replace("/admin/login"); setRows(await response.json()); };
  // The loader is intentionally shared by tab actions and this effect.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (!token) router.replace("/admin/login"); else load(); }, [tab, token]);
  const updateStatus = async (id: string, status: string) => { await fetch(`${endpoint}/${id}`, { method: "PUT", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); load(); };
  const remove = async (id: string) => { if (!confirm("Delete this record?")) return; await fetch(`${endpoint}/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); load(); };
  const edit = async (row: any) => { const name = prompt("Name / title", row.name || row.title || row.author); if (!name) return; const data = row.name !== undefined ? { name } : row.title !== undefined ? { title: name } : { author: name }; await fetch(`${endpoint}/${row.id}`, { method: "PUT", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(data) }); load(); };
  const add = async () => { const payload = tab === "Menu" ? { name: form.name, description: form.description, price: form.price, category: form.category || "starters", dietary: (form.dietary || "").split(",").map((x) => x.trim()).filter(Boolean), image: form.image } : tab === "Testimonials" ? { author: form.author, quote: form.quote, role: form.role, rating: form.rating } : { title: form.title, url: form.url, caption: form.caption, category: form.category }; await fetch(endpoint, { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(payload) }); setForm({}); load(); };
  const fields = tab === "Menu" ? ["name", "description", "price", "category", "dietary", "image"] : tab === "Testimonials" ? ["author", "quote", "role", "rating"] : tab === "Gallery" ? ["title", "url", "category", "caption"] : [];
  return <main className="min-h-screen bg-[var(--cream-2)] pt-28 pb-20 px-4 sm:px-6"><div className="max-w-6xl mx-auto"><div className="flex flex-wrap items-end justify-between gap-4 mb-8"><div><p className="text-[10px] uppercase tracking-[.25em] text-[var(--flame)] font-bold">The Garden Table</p><h1 className="font-display text-4xl sm:text-5xl">Admin Desk</h1></div><button onClick={() => { localStorage.removeItem("gt-admin-token"); router.replace("/admin/login"); }} className="btn-2d bg-[var(--card)] px-4 py-2 text-xs uppercase">Sign out</button></div><div className="flex flex-wrap gap-2 mb-7">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`btn-2d px-4 py-2 text-xs uppercase ${tab === item ? "bg-[var(--flame)] text-[var(--card)]" : "bg-[var(--card)]"}`}>{item}</button>)}</div>{fields.length > 0 && <div className="sketch bg-[var(--card)] p-4 mb-7"><h2 className="font-display text-2xl mb-3">Add {tab.slice(0, -1)}</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">{fields.map((field) => <input key={field} value={form[field] || ""} onChange={(e) => setForm({ ...form, [field]: e.target.value })} placeholder={field} className={input} />)}<button onClick={add} className="btn-2d justify-center bg-[var(--butter)] px-4 py-2 text-xs uppercase">Add record</button></div></div>}<div className="sketch bg-[var(--card)] overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b-[3px] border-[var(--ink)]"><tr><th className="p-4">Record</th><th className="p-4">Details</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b-2 border-[var(--ink)]/15"><td className="p-4 min-w-48"><b className="font-display text-lg">{row.name || row.title || row.author || row.customerName}</b><span className="block text-[10px] opacity-60">{row.id}</span></td><td className="p-4 max-w-sm">{row.description || row.quote || row.caption || (row.items && `${row.items.length} item(s)`) || row.email}</td><td className="p-4">{tab === "Reservations" ? <select value={row.status} onChange={(e) => updateStatus(row.id, e.target.value)} className={input}><option>pending</option><option>confirmed</option><option>cancelled</option></select> : tab === "Orders" ? <select value={row.status} onChange={(e) => updateStatus(row.id, e.target.value)} className={input}><option>new</option><option>preparing</option><option>done</option></select> : <span className="text-[var(--olive)]">{row.price ? `£${row.price}` : row.rating ? `${row.rating}/5` : "Active"}</span>}</td><td className="p-4 whitespace-nowrap"><button onClick={() => edit(row)} className="underline mr-3">Edit</button>{!(["Reservations", "Orders"].includes(tab)) && <button onClick={() => remove(row.id)} className="text-[var(--flame)] underline">Delete</button>}</td></tr>)}</tbody></table>{!rows.length && <p className="p-8 text-center font-display text-xl">No records yet.</p>}</div></div></main>;
}
