"use client";
import { FormEvent, useState } from "react";
import { Eye, EyeOff, LockKeyhole, Mail, Sprout } from "lucide-react";
import { useRouter } from "next/navigation";

export default function AdminLogin() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); setLoading(false); if (!response.ok) return setError(data.error || "Invalid credentials"); localStorage.setItem("gt-admin-token", data.token); router.replace("/admin"); };
  return <main className="relative min-h-screen bg-[var(--sage)] grid place-items-center px-5 overflow-hidden"><Sprout className="absolute top-16 left-[12%] w-16 h-16 text-[var(--olive)] opacity-30 rotate-[-20deg]" /><span className="absolute right-[12%] bottom-20 text-7xl text-[var(--flame)] opacity-20">✦</span><form onSubmit={submit} className={`relative sketch comic-shadow bg-[var(--card)] w-full max-w-md p-7 sm:p-9 space-y-5 ${error ? "animate-[shake_.35s_ease-in-out]" : ""}`}><div className="text-center"><div className="mx-auto w-14 h-14 rounded-full border-[3px] border-[var(--ink)] bg-[var(--butter)] grid place-items-center comic-shadow-sm"><Sprout /></div><p className="text-[10px] uppercase tracking-[.25em] text-[var(--flame)] font-bold mt-4">The Garden Table</p><h1 className="font-display text-4xl mt-1">Back of House</h1><p className="text-xs mt-2">A quiet desk for the people behind the plates.</p></div><label className="block text-xs font-bold uppercase tracking-widest">Email<div className="relative mt-1"><Mail className="absolute left-3 top-3 w-4" /><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full border-[3px] border-[var(--ink)] bg-[var(--paper)] p-3 pl-10 text-sm" /></div></label><label className="block text-xs font-bold uppercase tracking-widest">Password<div className="relative mt-1"><LockKeyhole className="absolute left-3 top-3 w-4" /><input required type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} className="w-full border-[3px] border-[var(--ink)] bg-[var(--paper)] p-3 pl-10 pr-10 text-sm" /><button type="button" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"} className="absolute right-3 top-3"><>{show ? <EyeOff className="w-4" /> : <Eye className="w-4" />}</></button></div></label>{error && <p className="text-sm font-bold text-[var(--flame-deep)]">{error}</p>}<div className="border-2 border-[var(--olive)] bg-[var(--sage)] p-3 text-xs"><b>Demo access</b><br />admin@thegardentable.com / admin123</div><button disabled={loading} className="btn-2d w-full justify-center px-5 py-4 bg-[var(--flame)] text-[var(--card)] uppercase text-xs tracking-widest disabled:opacity-60">{loading ? "Checking the ledger..." : "Enter Portal"}</button></form></main>;
}
